version: 2.1

jobs:
  build-and-test:
    executor: python/default  # Use the default Python executor

    steps:
      - checkout  # Checkout your code from the repository

      # Install dependencies within a virtual environment
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Create a virtual environment
            source venv/bin/activate  # Activate the virtual environment
            pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Add your specific build and test steps here (within the virtual environment)
      - run: echo "Building your project..."
      - run: echo "Running tests..."

      # (Optional) Push artifacts after successful build/test
      - store_artifacts:
          paths:
            - coverage/  # Example path to store test coverage reports

workflows:
  main:
    jobs:
      - build-and-test

