version: 2
jobs:
  build:
    docker:
      image: circleci/python:3.7 
    working_directory: ~/Deploy-06192024
    steps:
      # Checkout code from the Git repository (replace with actual checkout command)
      - checkout
         post:
	 #- pip install -U pip setuptools virtualenv

      # Create virtual environment and install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            echo "i am here `pwd`" 
            . venv/bin/activate
            #pip install -r requirements.txt
            a=`find . -type f -name "requirements.txt" -print` 
            pip install -r $a 

      - run:
          name: Install dependencies  Henry Omozuwa
          command: |
	      cat requirements.txt > /tmp/requirements.txt
	      pip install -r /tmp/requirements.txt
      # Run code style checks and unit tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics  # Include statistics for code style report
            pytest --junitxml=test-results/junit.xml  # Generate JUnit XML report

      # Store test results and artifacts
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
